# Generated by Django 3.2 on 2021-04-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cod_charge_percentage', models.FloatField(default=0)),
                ('return_charge_percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CostByAreaAndUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_title', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_by_unit', to='parcel_delivery.area')),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_invoice_id', models.CharField(max_length=4)),
                ('product_type', models.CharField(choices=[('Fragile', 'fragile'), ('Liquid', 'liquid')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='parcel_delivery.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_by_area_and_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_details', to='parcel_delivery.costbyareaandunit')),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parcel_delivery.parcel')),
            ],
        ),
    ]
