# Generated by Django 3.2 on 2021-04-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costbyareaandunit',
            old_name='quantity_title',
            new_name='quantity_cost_title',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='product_type',
            field=models.CharField(choices=[('fragile', 'Fragile'), ('liquid', 'Liquid')], max_length=10),
        ),
    ]
