# Generated by Django 3.2 on 2021-04-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_delivery', '0002_auto_20210424_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceByAreaAndUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_price_title', models.CharField(max_length=50)),
                ('price', models.FloatField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_by_area_unit', to='parcel_delivery.area')),
            ],
        ),
        migrations.RemoveField(
            model_name='parceldetails',
            name='cost_by_area_and_unit',
        ),
        migrations.DeleteModel(
            name='CostByAreaAndUnit',
        ),
        migrations.AddField(
            model_name='parceldetails',
            name='price_by_area_and_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parcel_details', to='parcel_delivery.pricebyareaandunit'),
            preserve_default=False,
        ),
    ]
